### ISSUE TITLE
What's going on with this, mate!!??

### ISSUE THREAD

**Issue by vaiRk** [GreasyBacon/spotifytestapp#1]

**Comment by GreasyBacon** [comment]
What do you mean @vaiRk? It's all up and running at https://mergeyoplaylists.today :D

**Comment by zakattack9** [comment]
Hey GreasyBacon, I'm not sure if you took this site down due to lack of use or it just got removed for some other reason, but I really loved this site. I can't tell you how much easier this makes making your favorite playlists into one. I was so bummed one day when it wouldn't load due to a "DNS connection". It seems as if the site is not accessible at all. This is pure genius and to go through all the work to code this, I believe it deserves more appreciation. I hope you can get the website back up and running.
-Zak

**Comment by GreasyBacon** [comment]
@zakattack9 thanks for the kind words. It's back up for the moment. I had temporarily shut it off for two reasons:
1. didn't think anyone used it
2. ongoing hosting costs in spite of point 1

**Comment by zakattack9** [comment]
Dude, thank you so much. This website creates new ways for me to listen and
explore new music. If it is to costly to maintain and host, all is ask is a
way to run this script at home so I have a means of merging playlists
without needing the website. Even though I'm a newbie at coding I'm sure
there's some way to run this code.

Thanks so much again,
Zak
